name: CI

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      TERRAFORM_STATE_TOKEN: ${{ secrets.TERRAFORM_STATE_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    

    - name: login to docker registry
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: build and push docker image to registry
      uses: docker/build-push-action@v5
      with:
        context: json-server/
        push: true
        tags: stormhenkel/json-server:lts
    
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install ansible

    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY }}'
        aws-secret-access-key: '${{ secrets.AWS_SECRET_KEY }}'
        aws-region: us-east-1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_wrapper: false
        cli_config_credentials_token: ${{ secrets.TERRAFORM_STATE_TOKEN }}
    - name: Terraform Apply
      id:   apply
      run: |
        cd app-server/
        terraform init
        terraform validate
        terraform plan 
        terraform apply -auto-approve

    - name: Parse Terraform output
      id: parse_output
      run: |
        IP=$(terraform output -json | jq -r '.instance_public_ip.value')
        echo "Server IP: $IP"
        echo "::set-output name=HOST_IP::$IP"
      working-directory: ./app-server

    - name: Add HOST IP to GitHub Secrets
      run: |
        echo $HOST_IP > /tmp/host_ip.txt
      env:
        HOST_IP: ${{ steps.parse_output.outputs.HOST_IP }}

