name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_TOKEN: ${{ secrets.TF_TOKEN }}
      ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
      HOST_IP: ${{ secrets.HOST_IP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install Github cli
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
          && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Authenticate AWS
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_KEY }}"
          aws-region: eu-west-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}
      - name: Terraform Apply
        id: apply
        run: |
          cd app-server/
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve

      - name: Parse Terraform output
        id: parse_output
        run: |
          IP=$(terraform output -json | jq -r '.instance_public_ip.value')
          echo "Server IP: $IP"
          echo "HOST_IP=$IP" >> $GITHUB_OUTPUT
        working-directory: ./app-server
    
      - name: Add HOST IP to GitHub Secrets
        run: |
          echo "${{ steps.parse_output.outputs.HOST_IP }}" > /tmp/host_ip.txt

      - name: Run Ansible playbooks
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          echo "Private key contents (first line):"
          head -n 1 private_key.pem
          echo "Attempting to connect to ${{ steps.parse_output.outputs.HOST_IP }}"
          ssh -i private_key.pem -o StrictHostKeyChecking=no -v $ANSIBLE_USER@${{ steps.parse_output.outputs.HOST_IP }} "echo 'SSH connection successful'"
          ansible-playbook -i "${{ steps.parse_output.outputs.HOST_IP }}," \
            --private-key=private_key.pem \
            -u $ANSIBLE_USER \
            -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
            -vvv \
            playbooks/deploy-server.yml
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}