name: tfdestroy

on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: EC2 name
        required: false
        default: 'App Server'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      TERRAFORM_STATE_TOKEN: ${{ secrets.TERRAFORM_STATE_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY }}'
        aws-secret-access-key: '${{ secrets.AWS_SECRET_KEY }}'
        aws-region: eu-west-2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_wrapper: false
        cli_config_credentials_token: ${{ secrets.TERRAFORM_STATE_TOKEN }}
    - name: Terraform Destroy
      id:   destroy
      run: |
        cd app-server/
        terraform init
        terraform destroy -auto-approve